### ISSUE TITLE
DEAD? 

### ISSUE THREAD

**Issue by alejzeis** [LegendOfMCPE/PocketBot#1]
This looks like the project is dead...

**Comment by falkirks** [comment]
I haven't had any spare time to work on it :(

**Comment by PEMapModder** [comment]
I don't have time to do it either. You can make pulls still though :)

**Comment by alejzeis** [comment]
Lol.

On Saturday, July 12, 2014, PEMapModder notifications@github.com wrote:

> I don't have time to do it either. You can make pulls still though :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LegendOfMCPE/FakeClient/issues/1#issuecomment-48818175
> .

##
