### ISSUE TITLE
com.github.legendofmcpe.pocketbot.Runner is missing

### ISSUE THREAD

**Issue by pcbeard** [LegendOfMCPE/PocketBot#4]
If you run the command:

ant run

it fails like this:

run:
     [java] Error: Could not find or load main class com.github.legendofmcpe.pocketbot.Runner
     [java] Java Result: 1

**Comment by alejzeis** [comment]
@pcbeard This is not really actively developed.

**Comment by pcbeard** [comment]
I think the file "used" to exist. Should the code still work with 0.10.4? I've observed that the Udp packet for OPEN_CONNECTION_REPLY_2 is now 1 + 34 bytes, but OPEN_CONNECTION_REPLY_2.decode() only reads 16 + 8 + 2 + 2 + 1 = 29 bytes.

**Comment by PEMapModder** [comment]
We paused development on it.
